---

- name: Get vpc details for "{{ ec2_vpc }}"
  ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ ec2_vpc }}"
    region: "{{ ec2_region }}"
  register: r_ec2_vpc_app

- debug: 
    var: r_ec2_vpc_app

- name: Get default SG for "{{ ec2_vpc }}"  VPC
  ec2_group_facts:
    filters:
      group-name: default
      vpc_id: "{{ r_ec2_vpc_app.vpcs.0.id }}"
    region: "{{ ec2_region }}"
  register: r_app_default_sg

- name: Remove SSH from lab VPC to default SG for "{{ ec2_vpc }}"
  ec2_group:
    name: default
    region: "{{ ec2_region }}"
    vpc_id: "{{ r_ec2_vpc_app.vpcs.0.id }}"
    description: default VPC security group
    purge_rules: yes
    rules:
      - proto: all
        group_id: "{{ r_app_default_sg.security_groups.0.group_id }}"

- name: Find peering facts
  ec2_vpc_peering_facts:
    region: "{{ ec2_region }}"
    filters:
      "tag:Name": "{{ ec2_app }}_peering"    
  register: r_vpc_peers

- debug: 
    var: r_vpc_peers

- name: Remove Peering
  ec2_vpc_peer:
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_lab_vpc_id }}"
    peering_id: "{{ r_vpc_peers.result.0.vpc_peering_connection_id }}"
    state: absent

- name: Get NAT gateway facts
  ec2_vpc_nat_gateway_facts:
    region: "{{ ec2_region }}"
    filters: 
      vpc-id: "{{ r_ec2_vpc_app.vpcs.0.id }}"
  register: r_nat

- debug:
    var: r_nat

- name: Remove NAT gateway
  ec2_vpc_nat_gateway:
    state: absent
    region: "{{ ec2_region }}"
    nat_gateway_id: "{{ r_nat.result.0.nat_gateway_id }}"
    wait: yes
    release_eip: yes
  when: r_nat.result.0.nat_gateway_id is defined

- name: Find default route table ID for lab VPC
  ec2_vpc_route_table_facts:
    filters:
      vpc-id: "{{ ec2_lab_vpc_id }}"
    region: "{{ ec2_region }}"
  register: r_lab_route

- debug:
    var: r_lab_route

- name: Remove peering for "{{r_ec2_vpc_peer.peering_id }}" route for lab VPC
  ec2_vpc_route_table:
    vpc_id:  "{{ ec2_lab_vpc_id }}"
    region: "{{ ec2_region }}"
    route_table_id: "{{ r_lab_route.route_tables.0.id }}"
    routes:
      - dest: "{{ item.value.dest  }}"
        "": "{{r_ec2_vpc_peer.peering_id }}"
    loop: "{{ r_lab_route.route_tables.0.routes }}"
    when: 

# - name: Find route ID for lab VPC
#   ec2_vpc_route_table_facts:
#     filters:
#       vpc-id: "{{ ec2_lab_vpc_id }}"
#     region: "{{ ec2_region }}"
#   register: r_lab_route

# - name: Update route for lab VPC
#   ec2_vpc_route_table:
#     vpc_id:  "{{ ec2_lab_vpc_id }}"
#     region: "{{ ec2_region }}"
#     route_table_id: "{{ r_lab_route.route_tables.0.id }}"
#     routes:
#       - dest: "{{ ec2_sub_cidr_prefix  }}"
#         vpc_peering_connection_id: "{{r_ec2_vpc_peer.peering_id }}"

# - name: Find route ID for "{{ ec2_vpc }}" VPC
#   ec2_vpc_route_table_facts:
#     filters:
#       vpc-id: "{{ r_ec2_vpc_app.vpc.id }}"
#     region: "{{ ec2_region }}"
#   register: r_app_route

# - debug: 
#     var: r_app_route

# - debug:
#     var:
#       - r_ec2_vpc_app.vpc.id  
#       -  r_app_route.route_tables.0.id 

# - name: Update route for lab VPC
#   ec2_vpc_route_table:
#     vpc_id:  "{{ r_ec2_vpc_app.vpc.id }}"
#     region: "{{ ec2_region }}"
#     route_table_id: "{{ r_app_route.route_tables.0.id }}"
#     routes:
#       - dest: 10.0.0.0/16
#         vpc_peering_connection_id: "{{ r_ec2_vpc_peer.peering_id }}"

# - name: Delete Peering

# - name: Delete VPC

