---
- name: Create a VPC "{{ ec2_vpc }}"
  ec2_vpc_net:
    name: "{{ ec2_vpc }}"
    cidr_block: "{{ ec2_app_cidr}}"
    region: "{{ ec2_region }}"
    state: present
    tags: 
      Name: "{{ ec2_vpc }}" 
  register: r_ec2_vpc_app

- name: Create a public subnet in "{{ ec2_vpc }}"
  ec2_vpc_subnet:
    vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    az: "{{ ec2_region }}a"
    cidr: "{{ ec2_app_cidr_pub }}"
    region: "{{ ec2_region }}"
    resource_tags:
      Name: "{{ ec2_subnet_name }}_pub"
    state: present
    tags: 
      - Name: "{{ ec2_vpc }}_pub" 
  register: r_ec2_subnet_app_pub

- name: Create a LB public subnet in "{{ ec2_vpc }}"
  ec2_vpc_subnet:
    vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    cidr: "{{ ec2_app_cidr_pub_lb }}"
    region: "{{ ec2_region }}"
    az: "{{ ec2_region }}b"
    resource_tags:
      Name: "{{ ec2_subnet_name }}_pub_lb"
    state: present
    tags: 
      - Name: "{{ ec2_vpc }}_pub_lb" 
  register: r_ec2_subnet_app_pub_lb

- name: Create a private subnet in "{{ ec2_vpc }}"
  ec2_vpc_subnet:
    vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    cidr: "{{ ec2_app_cidr_prv }}"
    region: "{{ ec2_region }}"
    resource_tags:
      Name: "{{ ec2_subnet_name }}_prv"
    state: present
    tags: 
      Name: "{{ ec2_vpc }}_prv" 
  register: r_ec2_subnet_app_prv

- name: Create igw in "{{ ec2_vpc }}" 
  ec2_vpc_igw:
    region: "{{ ec2_region }}"
    vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    state: present
    tags: 
      Name: "{{ ec2_app }}_igw" 
  register: r_igw

- name: Create natgw in "{{ ec2_vpc }}" 
  ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ r_ec2_subnet_app_pub.subnet.id }}" 
    wait: no
    if_exist_do_not_create: yes
    region: "{{ ec2_region }}"
  register: r_nat_gateway

- name: Peer Ansible VPC to "{{ ec2_vpc }}" 
  ec2_vpc_peer:
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_lab_vpc_id }}"
    peer_vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    state: present
    tags: 
      Name: "{{ ec2_app }}_peering" 
  register: r_ec2_vpc_peer

- name: Accept peering connection from remote account
  ec2_vpc_peer:
    region: "{{ ec2_region }}"
    peering_id: "{{ r_ec2_vpc_peer.peering_id }}"
    state: accept

- name: Get facts for default SG of Ansible VPC
  ec2_group_facts:
    filters:
      group-name: default
      vpc_id: "{{ ec2_lab_vpc_id }}"
    region: "{{ ec2_region }}"
  register: r_lab_default_sg

- name: Extract SG info
  set_fact: 
    lab_sg: "{{ r_lab_default_sg.security_groups.0 }}"

- name: Get default SG for "{{ ec2_vpc }}" VPC
  ec2_group_facts:
    filters:
      group-name: default
      vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    region: "{{ ec2_region }}"
  register: r_app_default_sg

- name: Add HTTP from all & SSH from Ansible VPC to default SG for "{{ ec2_vpc }}"
  ec2_group:
    name: default
    region: "{{ ec2_region }}"
    vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    description: default VPC security group
    purge_rules: yes
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        group_id: "{{ lab_sg.owner_id }}/{{ lab_sg.group_id }}/{{ lab_sg.group_name }}"
      - proto: tcp
        from_port: "{{ ec2_lb_target_port }}"
        to_port: "{{ ec2_lb_target_port }}"
        cidr_ip: 0.0.0.0/0
      - proto: all
        group_id: "{{ r_app_default_sg.security_groups.0.group_id }}"

- name: Find default route table ID for lab VPC
  ec2_vpc_route_table_facts:
    filters:
      vpc-id: "{{ ec2_lab_vpc_id }}"
    region: "{{ ec2_region }}"
  register: r_lab_route

- name: Update default route table for Ansible VPC to peering VPC
  ec2_vpc_route_table:
    vpc_id:  "{{ ec2_lab_vpc_id }}"
    region: "{{ ec2_region }}"
    route_table_id: "{{ r_lab_route.route_tables.0.id }}" 
    purge_routes: no
    lookup: id
    routes:
      - dest: "{{ ec2_app_cidr }}"
        vpc_peering_connection_id: "{{r_ec2_vpc_peer.peering_id }}"
  # Add route existence check
  ignore_errors: yes

- name: Find default route table ID for "{{ ec2_vpc }}" VPC
  ec2_vpc_route_table_facts:
    filters:
      vpc-id: "{{ r_ec2_vpc_app.vpc.id }}"
    region: "{{ ec2_region }}"
  register: r_app_route

- debug: 
    var: r_app_route
    verbosity: 2

- name: Update default route table for app in "{{ ec2_vpc }}" VPC for igw
  ec2_vpc_route_table:
    vpc_id:  "{{ r_ec2_vpc_app.vpc.id }}"
    region: "{{ ec2_region }}"
    route_table_id: "{{ r_app_route.route_tables.0.id }}"
    purge_routes: no
    lookup: id
    #tags:
    #  Name: "{{ ec2_vpc }}_pub" 
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ r_igw.gateway_id }}"
  # Add route existence check
  ignore_errors: yes
  when: r_igw.changed

- name: Create route table for the private network of "{{ ec2_vpc }}" VPC with NAT and Peering
  ec2_vpc_route_table:
    vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    region: "{{ ec2_region }}"
    #tags:
    #  Name: "{{ ec2_vpc }}_prv" 
    subnets:
      - "{{ r_ec2_subnet_app_prv.subnet.id }}" 
    routes:
      - dest: 0.0.0.0/0
        gateway_id:  "{{ r_nat_gateway.nat_gateway_id }}" 
      - dest: 10.0.0.0/16
        vpc_peering_connection_id: "{{ r_ec2_vpc_peer.peering_id }}"

- name: Create Target Group
  elb_target_group:
    name: "{{ ec2_lb_target }}" 
    region: "{{ ec2_region }}"
    protocol: http
    port: "{{ ec2_lb_target_port }}"
    vpc_id:  "{{ r_ec2_vpc_app.vpc.id }}"
    health_check_path: /
    successful_response_codes: "200,250-260"
    state: present

- name: Create Load Balancer
  elb_application_lb:
    name: "{{ ec2_lb_name }}" 
    region: "{{ ec2_region }}"
    security_groups:
      -  "{{ r_app_default_sg.security_groups.0.group_id }}"
    subnets:
      - "{{ r_ec2_subnet_app_pub.subnet.id }}"
      - "{{ r_ec2_subnet_app_pub_lb.subnet.id }}"
    listeners:
      - Protocol: HTTP 
        Port: "{{ ec2_lb_target_port }}" 
        DefaultActions:
          - Type: forward 
            TargetGroupName:  "{{ ec2_lb_target }}" 
    state: present
  register: r_alb

- name: Record needed facts from the newly provisioned infrastructure
  set_fact:
    cat_facts: 
      ec2_vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
      ec2_subnet_id: "{{ r_ec2_subnet_app_prv.subnet.id }}"
      lb_fqdn: "{{ r_alb.dns_name }}"
  delegate_to: fact_store
  delegate_facts: yes
  run_once: yes






