---
- name: Delete SG rule to peer

- name: Get vpc details for "{{ ec2_vpc }}"
  ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ ec2_vpc }}"
  register: r_ec2_vpc_app

- name: Get default SG for "{{ ec2_vpc }}"  VPC
  ec2_group_facts:
    filters:
      group-name: default
      vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    region: "{{ ec2_region }}"
  register: r_app_default_sg

- name: Remove SSH from lab VPC to default SG for "{{ ec2_vpc }}"
  ec2_group:
    name: default
    region: "{{ ec2_region }}"
    vpc_id: "{{ r_ec2_vpc_app.vpc.id }}"
    description: default VPC security group
    purge_rules: yes
    rules:
      - proto: all
        group_id: "{{ r_app_default_sg.security_groups.0.group_id }}"

# - name: Remove route to peer 

# - name: Delete Peering

# - name: Delete VPC

